#+TITLE:  Research Lab
#+AUTHOR: VLEAD
#+DATE: [2018-10-01 Thu]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil
#+PROPERTY: results output
#+PROPERTY: exports doc
#+LATEX: Literal LaTeX code for export

* Introduction
  This is document details the structure of the Choppella's research
  lab web pages and the steps to be followed to update the content of
  the pages.

* Repository
  Follow the [[https://github.com/vlead/choppella-research-pages][link]] to access the repository of Gitlab containing
  sources of these pages.

* Structure 
  This repository is organized as follows : 
  Structure and the purpose of each each directory 
  
  
* Steps to add content for pages
** Index 
   Include all the pages in the index. 
** Header section 
   Purpose :: Header section consists logo research lab name and search bar.
   Filename with link :: header.org
   Instructions :: Needs to be update the logo and name if needed. 
   1. Go to the header.org
   2. Change the logo and name 
** Slider section 
   Purpose :: Slider section consists :  
    1. Slider :  slider will slide different posters
    2. Latest updates : Latest updates will have current updates of positions.
    3. Filename with link :: slider.org
    

** Home
   Home section consists details of about research lab, content should
   add in the section of home tab/menu on profile.org

** Team
   Team section consists students details like photo, name and
   research topic.  photos (Professor/Students) needs to be update.
   content should add in the section of team tab/menu on profile.org

** Research 
   Research section consists research areas and funded projects
   details.  content added from the Content added from the pascal [[http://pascal.iiit.ac.in/~choppell/research/][link]]
   website content should add in the section of research tab/menu on
   profile.org
** Publications 
   Publicaitons section consists detaisl of all published papers like
   paper title, conference details, author names, DOI details (along
   with url), website details (along with url), published year and
   pages.  content added from the Content added from the pascal [[http://pascal.iiit.ac.in/~choppell/research/][link]]
   website
   
** Teaching  
   Teaching section consists detaisl of all teaching topics content
   added from the Content added from the pascal [[http://pascal.iiit.ac.in/~choppell/research/][link]] website if more
   content needs to be added update the content in the section of
   teaching tab/menu on profile.org

** Job 
   Job Section consists details of current positions like PhD
   Positions, MS by Research Positions, 2018 Summer Internships and
   BTech and MTech Projects. if more content needs to be added update
   the content in the section of job tab/menu on profile.org
   
** Contact 
   Contact Section consists details of research lab Location, Mail
   address, office/admin Phone numbers, professor email id, route map,
   Office Hours for 2018 Monsoon and Appointment details. all details
   added form the pascal [[http://pascal.iiit.ac.in/~choppell/research/][link]] website.  if more details needs to be
   added, update in the section of contact tab/menu on profile.org
** Footer section 
   footer section consists only insitute logo and research lab name
   details. if more details needs to be added, update in the section
   of footer section on profile.org

** Styling 
   Purpose 
   File 
   
* Steps to build and test 
* Steps to host 
