#+TITLE:  Choppella Research Lab
#+AUTHOR: VLEAD
#+DATE: [2018-10-01 Thu]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil
#+PROPERTY: results output
#+PROPERTY: exports doc
#+LATEX: Literal LaTeX code for export

* Introduction
  This document details the structure of the Choppella's
  research lab web pages and the steps to be followed to
  update the content of the pages.
* Repository 
  Follow the [[https://github.com/vlead/choppella-research-pages][link]] to access the repository of Gitlab
  containing sources of these pages.

* Structure 
  This repository is organized as follows : 
** Structure of the repo
   The repository must have a src folder and all the source files must
   be under src directory.  Example ::
   #+BEGIN_EXAMPLE
  |---README.org
  |---make
  |---init
  |---index.org
      |---src
          |---header.org
          |---slider.org
	  |---home.org
	  |---team.org
          |---research.org
	  |---publication.org
	  |---teaching.org
	  |---jobs.org
	  |---contact.org
          |---style
	       |---style 
	           |---style.css
	       |---js
	           |---main.js
    #+END_EXAMPLE



* Steps to build 
  Since code is situated within the narrative, one has to
  build these documents to generate code and documents for
  publication. While the code is understood by the compiler,
  the documents will be published in html.

** Steps to build and run the appliciton
   Refer to a sample makefile for reference. 

    #+BEGIN_EXAMPLE
    
    #SHELL := /bin/bash
    CODE_DIR=build/code
    PWD=$(shell pwd)
    LINT_FILE=${PWD}/${CODE_DIR}/lint_output
    EXIT_FILE=${PWD}/exit.txt
    STATUS=0
    
    all:  build
    
    init: 
    ./init.sh
    
    build: init
    make -f tangle-make -k all
    
    clean:	
         make -f tangle-make clean
    
    #+END_EXAMPLE

   
   
** Run the following command to build 
   =make -k all=
** Build Directory and .gitignore
   The build process generates a build folder containing
   docs and code directories. This build folder is not
   version controlled since it is generated and to allow git
   to ignore generated files.

    #+BEGIN_EXAMPLE

    build/
    code/
    docs/
    elisp/
    style/
    src/style
    elisp          
    #+END_EXAMPLE

    
* Steps to host and test
  
  - Host source files (build) in the respective server
    
* Steps to add content for pages
** Index.org 
   Purpose :: This file contains all source (.org) pages. 

   Filename with link :: [[https://github.com/vlead/choppella-research-pages/blob/master/index.org][index]].org

   Instructions ::
   1. Include all pages in the index.org using the following
      command example: =#+include: "./src/header.org"=

** Header section 
   Purpose :: Header section consists logo and Research Lab name.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/header.org][header.org]]

   Instructions::
   1. Go to the header.org
   2. Change the logo and name 

** Slider section 
   Purpose:: Slider section consists of 
   1. Slider : Slide show of various poster/Images 
   2. Latest updates : Latest news at Research Lab.  Basic Content
      added as per your pascal ( ) pages. Need list and links to
      relevant posters/images that you want to display.
      
   Filename with link :: [[https://github.com/vlead/choppella-research-pages/blob/master/src/slider.org][slider]].org
   
   Instructions :: 
   1. Go to the slider.org
   2. Upload the files on [[files.vlabs.ac.in/][fileserver]]
   3. Take the url and add in the slider section.
     
** Home
   
   Purpose:: This page captures the overview of the Research Lab. 
   Content should add in the home.org.  

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/home.org][home]].org 

   Instructions::
   1. Go to the home.org
   2. Add the content about search lab in the home menu. 

** Team
   Purpose:: This page captures the information of each student long
   with their pic, name and research topic. Required student
   information. Content should add in the team.org.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/students.org][team.org]]

   Instructions:: 
   1. Go to the team.org
   2. Upload photos on [[files.vlabs.ac.in/][fileserver]] and update url on team
      section.
   3. Add the student name in the "name field" and research
      topic name on "research-topic field".

** Research 
   Purpose:: This page captures all your research topics and funded
   project that yor are involved with. Basic content added from the Content added from the
   pascal([[http://pascal.iiit.ac.in/~choppell/research/][link)]] pages. Content should add in the research.org.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/research.org][research.org]]
   
   Instructions:: 
   1. Go to the research.org 
   2. Add research topic in the resection section. 
  
** Publications 
   Purpose:: This page captures all your publications with title,
   conference name, authors name, DOI number and website link (where
   the paper housted). It aslo allows one to filter the publications
   (like All publications, Conference Proceedings, Poster
   Publicaitons, Featured Publications and Journal Articles). Basic
   content added from the pascal([[http://pascal.iiit.ac.in/~choppell/research/][link]]) pages.
   
   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/publications.org][publications.org]]
   
   Instructions:: 
   1. Go to the publication.org
   2. Add publicaiton title, conference name, authors details, DOI
      details and published website details in the publicaiton menu
   
** Teaching  
   Purpose:: This page captures all courses taught by you till date
   Basic content added from pascal [[http://pascal.iiit.ac.in/~choppell/research/][link]] pages. If more content needs
   to be added update the content in the section of teaching.org.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/teaching.org][teaching]].org

   Instructions:: 
   1. Go to the teach.org
   2. Add course details in the teaching menu
   
** Job 
   Purpose:: This page captures the various positions available at
   Research Lab (PhD Positions, MS by Research Positions, 2018 Summer
   Internships and BTech and MTech Projects). Basic content added as
   per your pascal page.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/job.org][job.org]] 

   Instructions:: 
   1. Go to the job.org
   2. Add content about job details in the job menu
   
** Contact 
   Purpose:: This page captures the contact information about Research
   Lab (address, email, phone number and google map route, working
   hours and appointments) Basic Content added form the pascal( [[http://pascal.iiit.ac.in/~choppell/research/][link]] )
   website.  if more details needs to be added, update in the section
   of contact.org.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/contact-us.org][contact.org]]

   Instructions:: 
   1. Go to the contact.org
   2. Update the contact details in the job menu
   
** Footer section 
   Purpose:: This section consists of only Institute logo and Research
   Lab Name. 

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/blob/master/src/footer.org][footer]].org

   Instrucions:: 
   1. Go to the footer.org
   2. Add the details about lab details and copyright
      details.

** Styling 
   Purpose:: Style.org having whole website styling
   details. We can add enhancement stylings if needed more
   enhancements.

   Filename with link:: [[https://github.com/vlead/choppella-research-pages/style.org][styles]].org

   File Instruction:: 
   1. Go to the style.org 
   2. Add the stylings in the respective section for
      enhancements if needed.
   


